// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Topshelf")]
[assembly: AssemblyDescriptionAttribute("Topshelf is an open source project for hosting services without friction. By referencing Topshelf, your console application *becomes* a service installer with a comprehensive set of command-line options for installing, configuring, and running your application as a service.")]
[assembly: AssemblyProductAttribute("Topshelf")]
[assembly: AssemblyVersionAttribute("4.0.0.0")]
#if NETSTANDARD1_0 || NET40
[assembly: AssemblyFileVersion("4.0.0.0")]
#elif NETSTANDARD1_1 || WINDOWS8 || NET45 || NETCORE45
[assembly: AssemblyFileVersion("4.0.1000.0")]
#elif NETSTANDARD1_2 || WINDOWS81 || NET451 || NETCORE451 || WPA81
[assembly: AssemblyFileVersion("4.0.2000.0")]
#elif NETSTANDARD1_3 || NET46
[assembly: AssemblyFileVersion("4.0.3000.0")]
#elif NETSTANDARD1_4 || UAP10_0 || NETCORE50 || NET461
[assembly: AssemblyFileVersion("4.0.4000.0")]
#elif NETSTANDARD1_5 || NET462
[assembly: AssemblyFileVersion("4.0.5000.0")]
#elif NETSTANDARD1_6 || NETCOREAPP1_0 || NET463
[assembly: AssemblyFileVersion("4.0.6000.0")]
#else // this is here to prevent the build system from complaining. It should never be hit
[assembly: AssemblyFileVersion("4.0.9000.0")]
#endif
[assembly: AssemblyInformationalVersionAttribute("4.0.0-rtm-170501")]
[assembly: AssemblyCopyrightAttribute("Copyright 2012 Chris Patterson, Dru Sellers, Travis Smith, All rights reserved.")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Topshelf";
        internal const System.String AssemblyDescription = "Topshelf is an open source project for hosting services without friction. By referencing Topshelf, your console application *becomes* a service installer with a comprehensive set of command-line options for installing, configuring, and running your application as a service.";
        internal const System.String AssemblyProduct = "Topshelf";
        internal const System.String AssemblyVersion = "4.0.0.0";
        internal const System.String AssemblyFileVersion = "4.0.3.0";
        internal const System.String AssemblyInformationalVersion = "4.0.3.0 (develop/0b352d8c)";
        internal const System.String AssemblyCopyright = "Copyright 2012 Chris Patterson, Dru Sellers, Travis Smith, All rights reserved.";
    }
}
